# Generated by Django 4.2.30 on 2026-05-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D')], help_text='Class division (required for students and teachers).', max_length=5),
        ),
    ]
