# Generated by Django 4.2.30 on 2026-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('FY', 'F.Y'), ('SY', 'S.Y'), ('TY', 'T.Y'), ('BTECH', 'B.Tech')], help_text='Academic year/grade (students only).', max_length=10),
        ),
    ]
