# Generated by Django 4.2.30 on 2026-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the event.')),
                ('date', models.DateField(help_text='Date of the event.')),
                ('time', models.TimeField(help_text='Start time of the event.')),
                ('venue', models.CharField(help_text='Event venue/location.', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Only active events are shown to students.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
