# Generated by Django 4.2.30 on 2026-05-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D'), ('E', 'Division E'), ('F', 'Division F'), ('G', 'Division G'), ('H', 'Division H'), ('I', 'Division I'), ('J', 'Division J'), ('K', 'Division K'), ('L', 'Division L'), ('M', 'Division M'), ('N', 'Division N'), ('O', 'Division O'), ('P', 'Division P')], help_text='Class division (required for students and teachers).', max_length=5),
        ),
    ]
