# Generated by Django 4.2.30 on 2026-05-01 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator who reviewed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='event',
            field=models.ForeignKey(help_text='The event the student wants to attend.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to='events.event'),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='student',
            field=models.ForeignKey(help_text='The student who submitted this request.', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who reviewed this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerequest',
            unique_together={('student', 'event')},
        ),
    ]
