# Generated by Django 4.2.30 on 2026-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('coordinator_approved', 'Coordinator Approved'), ('coordinator_rejected', 'Coordinator Rejected'), ('teacher_approved', 'Teacher Approved'), ('teacher_rejected', 'Teacher Rejected')], db_index=True, default='pending', help_text='Current status in the approval workflow.', max_length=25)),
                ('reason', models.TextField(help_text='Why the student wants to attend this event.')),
                ('coordinator_remarks', models.TextField(blank=True, help_text="Coordinator's remarks on this request.")),
                ('coordinator_action_at', models.DateTimeField(blank=True, help_text='When the coordinator took action.', null=True)),
                ('teacher_remarks', models.TextField(blank=True, help_text="Teacher's remarks on this request.")),
                ('teacher_action_at', models.DateTimeField(blank=True, help_text='When the teacher took action.', null=True)),
                ('is_attended', models.BooleanField(default=False, help_text='Whether the student actually attended the event.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Request',
                'verbose_name_plural': 'Attendance Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
