# Generated by Django 4.2.30 on 2026-06-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('coordinator', 'Coordinator Event'),
                    ('open', 'Open Event'),
                ],
                db_index=True,
                default='coordinator',
                help_text='Coordinator Event follows full flow; Open Event skips coordinator and goes directly to teacher.',
                max_length=15,
            ),
        ),
    ]
