# Generated by Django 4.2.30 on 2026-06-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('attendance', '0003_attendancerequest_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='external_college_name',
            field=models.CharField(blank=True, help_text='College or institute hosting the external/open event.', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='external_event_date',
            field=models.DateField(blank=True, help_text='Date of the external/open event.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='external_event_location',
            field=models.CharField(blank=True, help_text='Location or venue of the external/open event.', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='external_event_name',
            field=models.CharField(blank=True, help_text='Name of the external/open event.', max_length=200),
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='external_event_time',
            field=models.TimeField(blank=True, help_text='Time of the external/open event.', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerequest',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The internal college event the student wants to attend.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_requests', to='events.event'),
        ),
    ]
